/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    /**
     * Testcase 1 for public String getGreeting()
     * 
     * This test verifies that the getGreeting method returns the expected string "Hello World!"
     */
    @Test
    public void test_getGreeting_1() {
        App app = new App();
        String result = app.getGreeting();
        assertEquals("Hello World!", result);
    }
}
